version: '3.7'
services:
  mysql_v5:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

  mysql_v8:
    image: mysql:8.4
    command: ["mysqld", "--mysql-native-password=ON"]
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test
  

  mariadb_v10_5:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

  mariadb_v10_6:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

  mariadb_v10_11:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

  mariadb_v11_4:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

  mariadb_v11_7:
    image: mariadb:11.7
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

