version: '3.7'
services:
  s3minio2025:
    image: minio/minio
    ports: ["9000:9000", "9001:9001"]
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_API_ROOT_ACCESS: on
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

