version: '3.7'
services:
  postgres_v17:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: integ_pass
      POSTGRES_DB: phorbas_test

  postgres_v16:
    image: postgres:16.8
    environment:
      POSTGRES_PASSWORD: integ_pass
      POSTGRES_DB: phorbas_test

  postgres_v15:
    image: postgres:15.12
    environment:
      POSTGRES_PASSWORD: integ_pass
      POSTGRES_DB: phorbas_test

  postgres_v14:
    image: postgres:14.17
    environment:
      POSTGRES_PASSWORD: integ_pass
      POSTGRES_DB: phorbas_test

  postgres_v13:
    image: postgres:13.20
    environment:
      POSTGRES_PASSWORD: integ_pass
      POSTGRES_DB: phorbas_test

  postgres_v9:
    image: postgres:9.6.24
    environment:
      POSTGRES_PASSWORD: integ_pass
      POSTGRES_DB: phorbas_test



  cockroach_v23:
    image: cockroachdb/cockroach:v23.2.23
    command: start-single-node --insecure

  cockroach_v22:
    image: cockroachdb/cockroach:v22.2.19
    command: start-single-node --insecure

