version: '3.7'
services:
  mongo:
    image: mongo

  mongo_v42:
    image: mongo:4.2
    #ports: ["27017:27017"]

  mongo_express:
    image: 'mongo-express'
    #ports: ['8081:8081']
    deploy: {replicas: 0}
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_v42


