version: '3.7'
networks:
  default: 
    attachable: true

services:
  sql_adminer:
    image: adminer
    ports: ['18082:8080']

  mitmproxy:
    image: mitmproxy/mitmproxy:5.1.1
    command: mitmweb --web-host 0.0.0.0
    ports: ['18081:8081']

  minio:
    image: minio/minio
    ports: ["9000:9000"]
    command: 'server /data'
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  phorbas_core:
    image: integ_phorbas_store_core
    ports: ["9099:9099"]
    command: 'npm -s run serve'

