version: '3.7'
services:
  mysql_v5:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

  mysql_v8:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test
  
  mariadb_v10_5:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

  mariadb_v10_6:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

  mariadb_v10_7:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: integ_pass
      MYSQL_DATABASE: phorbas_test

